DROP EXTENSION pg_net;
DROP EXTENSION pg_graphql;
CREATE ROLE supabase_privileged_role;
GRANT supabase_privileged_role TO postgres;
CREATE EXTENSION pg_cron WITH SCHEMA pg_catalog;
CREATE EXTENSION pg_net WITH SCHEMA public;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;
CREATE TABLE public.batting_stats (player_id text NOT NULL, avg double precision, ops double precision, games_played integer, games_started integer, at_bats integer, runs integer, hits integer, doubles integer, triples integer, home_runs integer, rbi integer, total_bases integer, slug_pct double precision, walks integer, hit_by_pitch integer, strikeouts integer, ob_pct double precision, stolen_bases integer, stolen_base_attempts integer, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.batting_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batting_stats ADD CONSTRAINT batting_stats_pkey PRIMARY KEY (player_id);
GRANT ALL ON public.batting_stats TO anon;
GRANT ALL ON public.batting_stats TO authenticated;
GRANT ALL ON public.batting_stats TO service_role;
CREATE POLICY "Public read access" ON public.batting_stats FOR SELECT USING (true);
CREATE TABLE public.games (id text NOT NULL, date timestamp with time zone NOT NULL, opponent text NOT NULL, opponent_logo text, location text NOT NULL, venue text NOT NULL, city text NOT NULL, status text NOT NULL, iu_score integer, opponent_score integer, broadcast_network text, stream_url text, box_score_url text, is_conference_game boolean DEFAULT false, tournament_name text, notes text, innings_played text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now(), venue_lat double precision, venue_lon double precision, opponent_record text);
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.games ADD CONSTRAINT games_location_check CHECK (location = ANY (ARRAY['home'::text, 'away'::text, 'neutral'::text]));
ALTER TABLE public.games ADD CONSTRAINT games_pkey PRIMARY KEY (id);
ALTER TABLE public.games ADD CONSTRAINT games_status_check CHECK (status = ANY (ARRAY['upcoming'::text, 'live'::text, 'completed'::text, 'postponed'::text, 'canceled'::text]));
GRANT ALL ON public.games TO anon;
GRANT ALL ON public.games TO authenticated;
GRANT ALL ON public.games TO service_role;
CREATE POLICY "Public read access" ON public.games FOR SELECT USING (true);
CREATE TABLE public.news_articles (id text NOT NULL, title text NOT NULL, summary text NOT NULL, source text NOT NULL, url text NOT NULL, image_url text, published_date timestamp with time zone NOT NULL, category text, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.news_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news_articles ADD CONSTRAINT news_articles_pkey PRIMARY KEY (id);
GRANT ALL ON public.news_articles TO anon;
GRANT ALL ON public.news_articles TO authenticated;
GRANT ALL ON public.news_articles TO service_role;
CREATE POLICY "Public read access" ON public.news_articles FOR SELECT USING (true);
CREATE TABLE public.pitching_stats (player_id text NOT NULL, era double precision, wins integer, losses integer, games_played integer, games_started integer, complete_games integer, shutouts integer, saves integer, innings_pitched double precision, hits integer, runs integer, earned_runs integer, walks integer, strikeouts integer, opponent_avg double precision, whip double precision, updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.pitching_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pitching_stats ADD CONSTRAINT pitching_stats_pkey PRIMARY KEY (player_id);
GRANT ALL ON public.pitching_stats TO anon;
GRANT ALL ON public.pitching_stats TO authenticated;
GRANT ALL ON public.pitching_stats TO service_role;
CREATE POLICY "Public read access" ON public.pitching_stats FOR SELECT USING (true);
CREATE TABLE public.players (id text NOT NULL, number integer NOT NULL, first_name text NOT NULL, last_name text NOT NULL, "position" text NOT NULL, class_year text NOT NULL, hometown text NOT NULL, height_display text NOT NULL, headshot_url text, bats text, throws_hand text, created_at timestamp with time zone DEFAULT now(), updated_at timestamp with time zone DEFAULT now());
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ADD CONSTRAINT players_pkey PRIMARY KEY (id);
ALTER TABLE public.batting_stats ADD CONSTRAINT batting_stats_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id);
ALTER TABLE public.pitching_stats ADD CONSTRAINT pitching_stats_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id);
GRANT ALL ON public.players TO anon;
GRANT ALL ON public.players TO authenticated;
GRANT ALL ON public.players TO service_role;
CREATE POLICY "Public read access" ON public.players FOR SELECT USING (true);
CREATE TABLE public.rankings (id text NOT NULL, team_name text NOT NULL, rpi_rank integer, elo_rank integer, elo_value numeric, record text, conference text, last_updated timestamp with time zone DEFAULT now());
ALTER TABLE public.rankings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rankings ADD CONSTRAINT rankings_pkey PRIMARY KEY (id);
GRANT ALL ON public.rankings TO anon;
GRANT ALL ON public.rankings TO authenticated;
GRANT ALL ON public.rankings TO service_role;
CREATE POLICY "Allow public read" ON public.rankings FOR SELECT USING (true);
CREATE TABLE public.social_posts (id text NOT NULL, platform text NOT NULL, author text NOT NULL, author_handle text NOT NULL, content text NOT NULL, posted_date timestamp with time zone NOT NULL, likes integer DEFAULT 0, comments integer DEFAULT 0, shares integer DEFAULT 0, media_url text, post_url text, created_at timestamp with time zone DEFAULT now());
ALTER TABLE public.social_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_posts ADD CONSTRAINT social_posts_pkey PRIMARY KEY (id);
GRANT ALL ON public.social_posts TO anon;
GRANT ALL ON public.social_posts TO authenticated;
GRANT ALL ON public.social_posts TO service_role;
CREATE POLICY "Public read access" ON public.social_posts FOR SELECT USING (true);
